
# # place project specific paths in variables to make the rest of the script more generic
# variables:
#   EXE_RELEASE_FOLDER: 'YourApp\bin\Release'
#   MSI_RELEASE_FOLDER: 'Setup\bin\Release'
#   TEST_FOLDER: 'Tests\bin\Release'
#   DEPLOY_FOLDER: 'P:\Projects\YourApp\Builds'
#   NUGET_PATH: 'C:\Tools\NuGet\nuget.exe'
#   MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBbuild.exe'
#   NUNIT_PATH: 'C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe'

# Utilisation de l'image .net6.0
image : "mcr.microsoft.com/dotnet/sdk:6,0"

stages:
  - build
  - test

build_job:
  stage: build

  script:
    - echo "hello build"
    - dotnet build Ancestrel

  artifacts:
    expire_in: 1 week  # save gitlab server space, we copy the files we need to deploy folder later on

test_job:
  stage: test
  script:
    - dotnet test Ancestrel
  artifacts:
    when: always  # save test results even when the task fails
    expire_in: 1 week  # save gitlab server space, we copy the files we need to deploy folder later on

  dependencies:
    - build_job
