image : mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - test
# - release

build:
  stage: build
  script:
    - dotnet build ./Ancestrel/modelTests/ModelTests.csproj

test:
  stage: test
  script:
    - dotnet test

#release:
#  stage: release
#  only:
#    - master
#  artifacts:
#    paths:
#      - publish/
#  script:
#    - dotnet publish -c Release -o ../publish MyApp/MyApp.csproj