INSERT INTO PAYS VALUES('4', 'AF', 'AFG', 'Afghanistan', 'Afghanistan', 'Afghane')
INSERT INTO PAYS VALUES('8', 'AL', 'ALB', 'Albania', 'Albanie', 'Albanaise')
INSERT INTO PAYS VALUES('10', 'AQ', 'ATA', 'Antarctica', 'Antarctique', 'NULL')
INSERT INTO PAYS VALUES('12', 'DZ', 'DZA', 'Algeria', 'Algérie', 'Algérienne')
INSERT INTO PAYS VALUES('16', 'AS', 'ASM', 'American Samoa', 'Samoa Américaines', 'Américaine')
INSERT INTO PAYS VALUES('20', 'AD', 'AND', 'Andorra', 'Andorre', 'Andorrane')
INSERT INTO PAYS VALUES('24', 'AO', 'AGO', 'Angola', 'Angola', 'Angolaise')
INSERT INTO PAYS VALUES('28', 'AG', 'ATG', 'Antigua and Barbuda', 'Antigua-et-Barbuda', 'Antiguaise')
INSERT INTO PAYS VALUES('31', 'AZ', 'AZE', 'Azerbaijan', 'Azerbaïdjan', 'Azerbaïdjanaise')
INSERT INTO PAYS VALUES('32', 'AR', 'ARG', 'Argentina', 'Argentine', 'Argentine')
INSERT INTO PAYS VALUES('36', 'AU', 'AUS', 'Australia', 'Australie', 'Australienne')
INSERT INTO PAYS VALUES('40', 'AT', 'AUT', 'Austria', 'Autriche', 'Autrichienne')
INSERT INTO PAYS VALUES('44', 'BS', 'BHS', 'Bahamas', 'Bahamas', 'Bahamienne')
INSERT INTO PAYS VALUES('48', 'BH', 'BHR', 'Bahrain', 'Bahreïn', 'Bahreïnienne')
INSERT INTO PAYS VALUES('50', 'BD', 'BGD', 'Bangladesh', 'Bangladesh', 'Bangladaise')
INSERT INTO PAYS VALUES('51', 'AM', 'ARM', 'Armenia', 'Arménie', 'Arménienne')
INSERT INTO PAYS VALUES('52', 'BB', 'BRB', 'Barbados', 'Barbade', 'Barbadienne')
INSERT INTO PAYS VALUES('56', 'BE', 'BEL', 'Belgium', 'Belgique', 'Belge')
INSERT INTO PAYS VALUES('60', 'BM', 'BMU', 'Bermuda', 'Bermudes', 'Bermudienne')
INSERT INTO PAYS VALUES('64', 'BT', 'BTN', 'Bhutan', 'Bhoutan', 'Bhoutanaise')
INSERT INTO PAYS VALUES('68', 'BO', 'BOL', 'Bolivia', 'Bolivie', 'Bolivienne')
INSERT INTO PAYS VALUES('70', 'BA', 'BIH', 'Bosnia and Herzegovina', 'Bosnie-Herzégovine', 'Bosnienne')
INSERT INTO PAYS VALUES('72', 'BW', 'BWA', 'Botswana', 'Botswana', 'Botswanaise')
INSERT INTO PAYS VALUES('74', 'BV', 'BVT', 'Bouvet Island', 'Île Bouvet', 'Norvégienne')
INSERT INTO PAYS VALUES('76', 'BR', 'BRA', 'Brazil', 'Brésil', 'Brésilienne')
INSERT INTO PAYS VALUES('84', 'BZ', 'BLZ', 'Belize', 'Belize', 'Bélizienne')
INSERT INTO PAYS VALUES('86', 'IO', 'IOT', 'British Indian Ocean Territory', 'Territoire Britannique de l'Océan Indien', 'Britannique')
INSERT INTO PAYS VALUES('90', 'SB', 'SLB', 'Solomon Islands', 'Îles Salomon', 'Salomonaise')
INSERT INTO PAYS VALUES('92', 'VG', 'VGB', 'British Virgin Islands', 'Îles Vierges Britanniques', 'Britannique')
INSERT INTO PAYS VALUES('96', 'BN', 'BRN', 'Brunei Darussalam', 'Brunéi Darussalam', 'Brunéienne')
INSERT INTO PAYS VALUES('100', 'BG', 'BGR', 'Bulgaria', 'Bulgarie', 'Bulgare')
INSERT INTO PAYS VALUES('104', 'MM', 'MMR', 'Myanmar', 'Myanmar', 'Myanmaraise')
INSERT INTO PAYS VALUES('108', 'BI', 'BDI', 'Burundi', 'Burundi', 'Burundaise')
INSERT INTO PAYS VALUES('112', 'BY', 'BLR', 'Belarus', 'Bélarus', 'Biélorusse')
INSERT INTO PAYS VALUES('116', 'KH', 'KHM', 'Cambodia', 'Cambodge', 'Cambodgienne')
INSERT INTO PAYS VALUES('120', 'CM', 'CMR', 'Cameroon', 'Cameroun', 'Camerounaise')
INSERT INTO PAYS VALUES('124', 'CA', 'CAN', 'Canada', 'Canada', 'Canadienne')
INSERT INTO PAYS VALUES('132', 'CV', 'CPV', 'Cape Verde', 'Cap-vert', 'Capverdienne')
INSERT INTO PAYS VALUES('136', 'KY', 'CYM', 'Cayman Islands', 'Îles Caïmanes', 'Caïmanien')
INSERT INTO PAYS VALUES('140', 'CF', 'CAF', 'Central African', 'République Centrafricaine', 'Centrafricaine')
INSERT INTO PAYS VALUES('144', 'LK', 'LKA', 'Sri Lanka', 'Sri Lanka', 'Srilankaise')
INSERT INTO PAYS VALUES('148', 'TD', 'TCD', 'Chad', 'Tchad', 'Tchadienne')
INSERT INTO PAYS VALUES('152', 'CL', 'CHL', 'Chile', 'Chili', 'Chilienne')
INSERT INTO PAYS VALUES('156', 'CN', 'CHN', 'China', 'Chine', 'Chinoise')
INSERT INTO PAYS VALUES('158', 'TW', 'TWN', 'Taiwan', 'Taïwan', 'Taïwanaise')
INSERT INTO PAYS VALUES('162', 'CX', 'CXR', 'Christmas Island', 'Île Christmas', 'Australienne')
INSERT INTO PAYS VALUES('166', 'CC', 'CCK', 'Cocos (Keeling) Islands', 'Îles Cocos (Keeling)', 'Australienne')
INSERT INTO PAYS VALUES('170', 'CO', 'COL', 'Colombia', 'Colombie', 'Colombienne')
INSERT INTO PAYS VALUES('174', 'KM', 'COM', 'Comoros', 'Comores', 'Comorienne')
INSERT INTO PAYS VALUES('175', 'YT', 'MYT', 'Mayotte', 'Mayotte', 'Française')
INSERT INTO PAYS VALUES('178', 'CG', 'COG', 'Republic of the Congo', 'République du Congo', 'Congolaise')
INSERT INTO PAYS VALUES('180', 'CD', 'COD', 'The Democratic Republic Of The Congo', 'République Démocratique du Congo', 'Congolaise')
INSERT INTO PAYS VALUES('184', 'CK', 'COK', 'Cook Islands', 'Îles Cook', 'Cookien')
INSERT INTO PAYS VALUES('188', 'CR', 'CRI', 'Costa Rica', 'Costa Rica', 'Costaricienne')
INSERT INTO PAYS VALUES('191', 'HR', 'HRV', 'Croatia', 'Croatie', 'Croate')
INSERT INTO PAYS VALUES('192', 'CU', 'CUB', 'Cuba', 'Cuba', 'Cubaine')
INSERT INTO PAYS VALUES('196', 'CY', 'CYP', 'Cyprus', 'Chypre', 'Chypriote')
INSERT INTO PAYS VALUES('203', 'CZ', 'CZE', 'Czech Republic', 'République Tchèque', 'Tchèque')
INSERT INTO PAYS VALUES('204', 'BJ', 'BEN', 'Benin', 'Bénin', 'Béninoise')
INSERT INTO PAYS VALUES('208', 'DK', 'DNK', 'Denmark', 'Danemark', 'Danoise')
INSERT INTO PAYS VALUES('212', 'DM', 'DMA', 'Dominica', 'Dominique', 'Dominiquaise')
INSERT INTO PAYS VALUES('214', 'DO', 'DOM', 'Dominican Republic', 'République Dominicaine', 'Dominicaine')
INSERT INTO PAYS VALUES('218', 'EC', 'ECU', 'Ecuador', 'Équateur', 'Équatorienne')
INSERT INTO PAYS VALUES('222', 'SV', 'SLV', 'El Salvador', 'El Salvador', 'Salvadorienne')
INSERT INTO PAYS VALUES('226', 'GQ', 'GNQ', 'Equatorial Guinea', 'Guinée Équatoriale', 'Équatoguinéenne')
INSERT INTO PAYS VALUES('231', 'ET', 'ETH', 'Ethiopia', 'Éthiopie', 'Éthiopienne')
INSERT INTO PAYS VALUES('232', 'ER', 'ERI', 'Eritrea', 'Érythrée', 'Érythréenne')
INSERT INTO PAYS VALUES('233', 'EE', 'EST', 'Estonia', 'Estonie', 'Estonienne')
INSERT INTO PAYS VALUES('234', 'FO', 'FRO', 'Faroe Islands', 'Îles Féroé', 'Féroïenne')
INSERT INTO PAYS VALUES('238', 'FK', 'FLK', 'Falkland Islands', 'Îles (malvinas) Falkland', 'Britannique')
INSERT INTO PAYS VALUES('239', 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'Géorgie du Sud et les Îles Sandwich du Sud', 'Britannique')
INSERT INTO PAYS VALUES('242', 'FJ', 'FJI', 'Fiji', 'Fidji', 'Fidjienne')
INSERT INTO PAYS VALUES('246', 'FI', 'FIN', 'Finland', 'Finlande', 'Finlandaise')
INSERT INTO PAYS VALUES('248', 'AX', 'ALA', 'Åland Islands', 'Îles Åland', 'Finlandaise')
INSERT INTO PAYS VALUES('250', 'FR', 'FRA', 'France', 'France', 'Française')
INSERT INTO PAYS VALUES('254', 'GF', 'GUF', 'French Guiana', 'Guyane Française', 'Française')
INSERT INTO PAYS VALUES('258', 'PF', 'PYF', 'French Polynesia', 'Polynésie Française', 'Française')
INSERT INTO PAYS VALUES('260', 'TF', 'ATF', 'French Southern Territories', 'Terres Australes Françaises', 'Française')
INSERT INTO PAYS VALUES('262', 'DJ', 'DJI', 'Djibouti', 'Djibouti', 'Djiboutienne')
INSERT INTO PAYS VALUES('266', 'GA', 'GAB', 'Gabon', 'Gabon', 'Gabonaise')
INSERT INTO PAYS VALUES('268', 'GE', 'GEO', 'Georgia', 'Géorgie', 'Géorgienne')
INSERT INTO PAYS VALUES('270', 'GM', 'GMB', 'Gambia', 'Gambie', 'Gambienne')
INSERT INTO PAYS VALUES('275', 'PS', 'PSE', 'Occupied Palestinian Territory', 'Territoire Palestinien Occupé', 'NULL')
INSERT INTO PAYS VALUES('276', 'DE', 'DEU', 'Germany', 'Allemagne', 'Allemande')
INSERT INTO PAYS VALUES('288', 'GH', 'GHA', 'Ghana', 'Ghana', 'Ghanéenne')
INSERT INTO PAYS VALUES('292', 'GI', 'GIB', 'Gibraltar', 'Gibraltar', 'Britannique')
INSERT INTO PAYS VALUES('296', 'KI', 'KIR', 'Kiribati', 'Kiribati', 'Kiribatienne')
INSERT INTO PAYS VALUES('300', 'GR', 'GRC', 'Greece', 'Grèce', 'Grecque')
INSERT INTO PAYS VALUES('304', 'GL', 'GRL', 'Greenland', 'Groenland', 'Groenlandaise')
INSERT INTO PAYS VALUES('308', 'GD', 'GRD', 'Grenada', 'Grenade', 'Grenadienne')
INSERT INTO PAYS VALUES('312', 'GP', 'GLP', 'Guadeloupe', 'Guadeloupe', 'Française')
INSERT INTO PAYS VALUES('316', 'GU', 'GUM', 'Guam', 'Guam', 'Finlandaise')
INSERT INTO PAYS VALUES('320', 'GT', 'GTM', 'Guatemala', 'Guatemala', 'Guatémaltèque')
INSERT INTO PAYS VALUES('324', 'GN', 'GIN', 'Guinea', 'Guinée', 'Guinéenne')
INSERT INTO PAYS VALUES('328', 'GY', 'GUY', 'Guyana', 'Guyana', 'Guyanienne')
INSERT INTO PAYS VALUES('332', 'HT', 'HTI', 'Haiti', 'Haïti', 'Haïtienne')
INSERT INTO PAYS VALUES('334', 'HM', 'HMD', 'Heard Island and McDonald Islands', 'Îles Heard et Mcdonald', 'Australienne')
INSERT INTO PAYS VALUES('336', 'VA', 'VAT', 'Vatican City State', 'Saint-Siège (état de la Cité du Vatican)', 'vaticane')
INSERT INTO PAYS VALUES('340', 'HN', 'HND', 'Honduras', 'Honduras', 'Hondurienne')
INSERT INTO PAYS VALUES('344', 'HK', 'HKG', 'Hong Kong', 'Hong-Kong', 'Hongkongaise')
INSERT INTO PAYS VALUES('348', 'HU', 'HUN', 'Hungary', 'Hongrie', 'Hongroise')
INSERT INTO PAYS VALUES('352', 'IS', 'ISL', 'Iceland', 'Islande', 'Islandaise')
INSERT INTO PAYS VALUES('356', 'IN', 'IND', 'India', 'Inde', 'Indienne')
INSERT INTO PAYS VALUES('360', 'ID', 'IDN', 'Indonesia', 'Indonésie', 'Indonésienne')
INSERT INTO PAYS VALUES('364', 'IR', 'IRN', 'Islamic Republic of Iran', 'République Islamique d'Iran', 'Iranienne')
INSERT INTO PAYS VALUES('368', 'IQ', 'IRQ', 'Iraq', 'Iraq', 'Irakienne')
INSERT INTO PAYS VALUES('372', 'IE', 'IRL', 'Ireland', 'Irlande', 'Irlandaise')
INSERT INTO PAYS VALUES('376', 'IL', 'ISR', 'Israel', 'Israël', 'Israélienne')
INSERT INTO PAYS VALUES('380', 'IT', 'ITA', 'Italy', 'Italie', 'Italienne')
INSERT INTO PAYS VALUES('384', 'CI', 'CIV', 'Côte d'Ivoire', 'Côte d'Ivoire', 'Ivoirienne')
INSERT INTO PAYS VALUES('388', 'JM', 'JAM', 'Jamaica', 'Jamaïque', 'Jamaïcaine')
INSERT INTO PAYS VALUES('392', 'JP', 'JPN', 'Japan', 'Japon', 'Japonaise')
INSERT INTO PAYS VALUES('398', 'KZ', 'KAZ', 'Kazakhstan', 'Kazakhstan', 'Kazakhe')
INSERT INTO PAYS VALUES('400', 'JO', 'JOR', 'Jordan', 'Jordanie', 'Jordanienne')
INSERT INTO PAYS VALUES('404', 'KE', 'KEN', 'Kenya', 'Kenya', 'Kényane')
INSERT INTO PAYS VALUES('408', 'KP', 'PRK', 'Democratic People's Republic of Korea', 'République Populaire Démocratique de Corée', 'Nord-Coréens')
INSERT INTO PAYS VALUES('410', 'KR', 'KOR', 'Republic of Korea', 'République de Corée', 'Sud-Coréenne')
INSERT INTO PAYS VALUES('414', 'KW', 'KWT', 'Kuwait', 'Koweït', 'Koweïtienne')
INSERT INTO PAYS VALUES('417', 'KG', 'KGZ', 'Kyrgyzstan', 'Kirghizistan', 'Kirghize')
INSERT INTO PAYS VALUES('418', 'LA', 'LAO', 'Lao People's Democratic Republic', 'République Démocratique Populaire Lao', 'Laotienne')
INSERT INTO PAYS VALUES('422', 'LB', 'LBN', 'Lebanon', 'Liban', 'Libanaise')
INSERT INTO PAYS VALUES('426', 'LS', 'LSO', 'Lesotho', 'Lesotho', 'Lesothane')
INSERT INTO PAYS VALUES('428', 'LV', 'LVA', 'Latvia', 'Lettonie', 'Lettone')
INSERT INTO PAYS VALUES('430', 'LR', 'LBR', 'Liberia', 'Libéria', 'Libérienne')
INSERT INTO PAYS VALUES('434', 'LY', 'LBY', 'Libyan Arab Jamahiriya', 'Jamahiriya Arabe Libyenne', 'Libyenne')
INSERT INTO PAYS VALUES('438', 'LI', 'LIE', 'Liechtenstein', 'Liechtenstein', 'Liechtensteinoise')
INSERT INTO PAYS VALUES('440', 'LT', 'LTU', 'Lithuania', 'Lituanie', 'Lituanienne')
INSERT INTO PAYS VALUES('442', 'LU', 'LUX', 'Luxembourg', 'Luxembourg', 'Luxembourgeoise')
INSERT INTO PAYS VALUES('446', 'MO', 'MAC', 'Macao', 'Macao', 'Macanaise')
INSERT INTO PAYS VALUES('450', 'MG', 'MDG', 'Madagascar', 'Madagascar', 'Malgache')
INSERT INTO PAYS VALUES('454', 'MW', 'MWI', 'Malawi', 'Malawi', 'Malawite')
INSERT INTO PAYS VALUES('458', 'MY', 'MYS', 'Malaysia', 'Malaisie', 'Malaisienne')
INSERT INTO PAYS VALUES('462', 'MV', 'MDV', 'Maldives', 'Maldives', 'Maldivienne')
INSERT INTO PAYS VALUES('466', 'ML', 'MLI', 'Mali', 'Mali', 'Malienne')
INSERT INTO PAYS VALUES('470', 'MT', 'MLT', 'Malta', 'Malte', 'Maltaise')
INSERT INTO PAYS VALUES('474', 'MQ', 'MTQ', 'Martinique', 'Martinique', 'Martiniquaise')
INSERT INTO PAYS VALUES('478', 'MR', 'MRT', 'Mauritania', 'Mauritanie', 'Mauritanienne')
INSERT INTO PAYS VALUES('480', 'MU', 'MUS', 'Mauritius', 'Maurice', 'Mauricienne')
INSERT INTO PAYS VALUES('484', 'MX', 'MEX', 'Mexico', 'Mexique', 'Mexicaine')
INSERT INTO PAYS VALUES('492', 'MC', 'MCO', 'Monaco', 'Monaco', 'Monégasque')
INSERT INTO PAYS VALUES('496', 'MN', 'MNG', 'Mongolia', 'Mongolie', 'Mongole')
INSERT INTO PAYS VALUES('498', 'MD', 'MDA', 'Republic of Moldova', 'République de Moldova', 'Moldaves')
INSERT INTO PAYS VALUES('500', 'MS', 'MSR', 'Montserrat', 'Montserrat', 'Britannique')
INSERT INTO PAYS VALUES('504', 'MA', 'MAR', 'Morocco', 'Maroc', 'Marocaine')
INSERT INTO PAYS VALUES('508', 'MZ', 'MOZ', 'Mozambique', 'Mozambique', 'Mozambicaine')
INSERT INTO PAYS VALUES('512', 'OM', 'OMN', 'Oman', 'Oman', 'Omanaise')
INSERT INTO PAYS VALUES('516', 'NA', 'NAM', 'Namibia', 'Namibie', 'Namibienne')
INSERT INTO PAYS VALUES('520', 'NR', 'NRU', 'Nauru', 'Nauru', 'Nauruane')
INSERT INTO PAYS VALUES('524', 'NP', 'NPL', 'Nepal', 'Népal', 'Népalaise')
INSERT INTO PAYS VALUES('528', 'NL', 'NLD', 'Netherlands', 'Pays-Bas', 'Néerlandaise')
INSERT INTO PAYS VALUES('530', 'AN', 'ANT', 'Netherlands Antilles', 'Antilles Néerlandaises', 'Néerlandaise')
INSERT INTO PAYS VALUES('533', 'AW', 'ABW', 'Aruba', 'Aruba', 'Néerlandaise')
INSERT INTO PAYS VALUES('540', 'NC', 'NCL', 'New Caledonia', 'Nouvelle-Calédonie', 'Calédonienne')
INSERT INTO PAYS VALUES('548', 'VU', 'VUT', 'Vanuatu', 'Vanuatu', 'Vanuatuane')
INSERT INTO PAYS VALUES('554', 'NZ', 'NZL', 'New Zealand', 'Nouvelle-Zélande', 'Néo-Zélandaise')
INSERT INTO PAYS VALUES('558', 'NI', 'NIC', 'Nicaragua', 'Nicaragua', 'Nicaraguayenne')
INSERT INTO PAYS VALUES('562', 'NE', 'NER', 'Niger', 'Niger', 'Nigérienne')
INSERT INTO PAYS VALUES('566', 'NG', 'NGA', 'Nigeria', 'Nigéria', 'Nigériane')
INSERT INTO PAYS VALUES('570', 'NU', 'NIU', 'Niue', 'Niué', 'Niouéenne')
INSERT INTO PAYS VALUES('574', 'NF', 'NFK', 'Norfolk Island', 'Île Norfolk', 'Australienne')
INSERT INTO PAYS VALUES('578', 'NO', 'NOR', 'Norway', 'Norvège', 'Norvégienne')
INSERT INTO PAYS VALUES('580', 'MP', 'MNP', 'Northern Mariana Islands', 'Îles Mariannes du Nord', 'Américaine')
INSERT INTO PAYS VALUES('581', 'UM', 'UMI', 'United States Minor Outlying Islands', 'Îles Mineures Éloignées des États-Unis', 'Américaine')
INSERT INTO PAYS VALUES('583', 'FM', 'FSM', 'Federated States of Micronesia', 'États Fédérés de Micronésie', 'Micronésienne')
INSERT INTO PAYS VALUES('584', 'MH', 'MHL', 'Marshall Islands', 'Îles Marshall', 'NULL')
INSERT INTO PAYS VALUES('585', 'PW', 'PLW', 'Palau', 'Palaos', 'Palauane')
INSERT INTO PAYS VALUES('586', 'PK', 'PAK', 'Pakistan', 'Pakistan', 'Pakistanaise')
INSERT INTO PAYS VALUES('591', 'PA', 'PAN', 'Panama', 'Panama', 'Panaméenne')
INSERT INTO PAYS VALUES('598', 'PG', 'PNG', 'Papua New Guinea', 'Papouasie-Nouvelle-Guinée', 'Papouasienne')
INSERT INTO PAYS VALUES('600', 'PY', 'PRY', 'Paraguay', 'Paraguay', 'Paraguayenne')
INSERT INTO PAYS VALUES('604', 'PE', 'PER', 'Peru', 'Pérou', 'Péruvienne')
INSERT INTO PAYS VALUES('608', 'PH', 'PHL', 'Philippines', 'Philippines', 'Philippine')
INSERT INTO PAYS VALUES('612', 'PN', 'PCN', 'Pitcairn', 'Pitcairn', 'britannique')
INSERT INTO PAYS VALUES('616', 'PL', 'POL', 'Poland', 'Pologne', 'Polonaise')
INSERT INTO PAYS VALUES('620', 'PT', 'PRT', 'Portugal', 'Portugal', 'Portugaise')
INSERT INTO PAYS VALUES('624', 'GW', 'GNB', 'Guinea-Bissau', 'Guinée-Bissau', 'Bissau-Guinéenne')
INSERT INTO PAYS VALUES('626', 'TL', 'TLS', 'Timor-Leste', 'Timor-Leste', 'Est-Timoraise')
INSERT INTO PAYS VALUES('630', 'PR', 'PRI', 'Puerto Rico', 'Porto Rico', 'Américaine')
INSERT INTO PAYS VALUES('634', 'QA', 'QAT', 'Qatar', 'Qatar', 'Qatarie')
INSERT INTO PAYS VALUES('638', 'RE', 'REU', 'Réunion', 'Réunion', 'Française')
INSERT INTO PAYS VALUES('642', 'RO', 'ROU', 'Romania', 'Roumanie', 'Roumaine')
INSERT INTO PAYS VALUES('643', 'RU', 'RUS', 'Russian Federation', 'Fédération de Russie', 'Russe')
INSERT INTO PAYS VALUES('646', 'RW', 'RWA', 'Rwanda', 'Rwanda', 'Rwandaise')
INSERT INTO PAYS VALUES('654', 'SH', 'SHN', 'Saint Helena', 'Sainte-Hélène', 'britannique')
INSERT INTO PAYS VALUES('659', 'KN', 'KNA', 'Saint Kitts and Nevis', 'Saint-Kitts-et-Nevis', 'Kittitienne')
INSERT INTO PAYS VALUES('660', 'AI', 'AIA', 'Anguilla', 'Anguilla', 'britannique')
INSERT INTO PAYS VALUES('662', 'LC', 'LCA', 'Saint Lucia', 'Sainte-Lucie', 'Saint-Lucienne')
INSERT INTO PAYS VALUES('666', 'PM', 'SPM', 'Saint-Pierre and Miquelon', 'Saint-Pierre-et-Miquelon', 'Française')
INSERT INTO PAYS VALUES('670', 'VC', 'VCT', 'Saint Vincent and the Grenadines', 'Saint-Vincent-et-les Grenadines', 'NULL')
INSERT INTO PAYS VALUES('674', 'SM', 'SMR', 'San Marino', 'Saint-Marin', 'Saint-Marinaise')
INSERT INTO PAYS VALUES('678', 'ST', 'STP', 'Sao Tome and Principe', 'Sao Tomé-et-Principe', 'Santoméenne')
INSERT INTO PAYS VALUES('682', 'SA', 'SAU', 'Saudi Arabia', 'Arabie Saoudite', 'Saoudienne')
INSERT INTO PAYS VALUES('686', 'SN', 'SEN', 'Senegal', 'Sénégal', 'Sénégalaise')
INSERT INTO PAYS VALUES('690', 'SC', 'SYC', 'Seychelles', 'Seychelles', 'Seychelloise')
INSERT INTO PAYS VALUES('694', 'SL', 'SLE', 'Sierra Leone', 'Sierra Leone', 'Sierra-Léonaise')
INSERT INTO PAYS VALUES('702', 'SG', 'SGP', 'Singapore', 'Singapour', 'Singapourienne')
INSERT INTO PAYS VALUES('703', 'SK', 'SVK', 'Slovakia', 'Slovaquie', 'Slovaque')
INSERT INTO PAYS VALUES('704', 'VN', 'VNM', 'Vietnam', 'Viet Nam', 'Vietnamienne')
INSERT INTO PAYS VALUES('705', 'SI', 'SVN', 'Slovenia', 'Slovénie', 'Slovène')
INSERT INTO PAYS VALUES('706', 'SO', 'SOM', 'Somalia', 'Somalie', 'Somalienne')
INSERT INTO PAYS VALUES('710', 'ZA', 'ZAF', 'South Africa', 'Afrique du Sud', 'Sud-Africaine')
INSERT INTO PAYS VALUES('716', 'ZW', 'ZWE', 'Zimbabwe', 'Zimbabwe', 'Zimbabwéenne')
INSERT INTO PAYS VALUES('724', 'ES', 'ESP', 'Spain', 'Espagne', 'Espagnole')
INSERT INTO PAYS VALUES('732', 'EH', 'ESH', 'Western Sahara', 'Sahara Occidental', 'NULL')
INSERT INTO PAYS VALUES('736', 'SD', 'SDN', 'Sudan', 'Soudan', 'Soudanaise')
INSERT INTO PAYS VALUES('740', 'SR', 'SUR', 'Suriname', 'Suriname', 'Surinamaise')
INSERT INTO PAYS VALUES('744', 'SJ', 'SJM', 'Svalbard and Jan Mayen', 'Svalbard etÎle Jan Mayen', 'Norvégienne')
INSERT INTO PAYS VALUES('748', 'SZ', 'SWZ', 'Swaziland', 'Swaziland', 'Eswatinienne')
INSERT INTO PAYS VALUES('752', 'SE', 'SWE', 'Sweden', 'Suède', 'Suédoise')
INSERT INTO PAYS VALUES('756', 'CH', 'CHE', 'Switzerland', 'Suisse', 'Suissesse')
INSERT INTO PAYS VALUES('760', 'SY', 'SYR', 'Syrian Arab Republic', 'République Arabe Syrienne', 'Syrienne')
INSERT INTO PAYS VALUES('762', 'TJ', 'TJK', 'Tajikistan', 'Tadjikistan', 'Tadjike')
INSERT INTO PAYS VALUES('764', 'TH', 'THA', 'Thailand', 'Thaïlande', 'Thaïlandaise')
INSERT INTO PAYS VALUES('768', 'TG', 'TGO', 'Togo', 'Togo', 'Togolaise')
INSERT INTO PAYS VALUES('772', 'TK', 'TKL', 'Tokelau', 'Tokelau', 'Néo-Zélandaise')
INSERT INTO PAYS VALUES('776', 'TO', 'TON', 'Tonga', 'Tonga', 'Tongienne')
INSERT INTO PAYS VALUES('780', 'TT', 'TTO', 'Trinidad and Tobago', 'Trinité-et-Tobago', 'Trinidadienne')
INSERT INTO PAYS VALUES('784', 'AE', 'ARE', 'United Arab Emirates', 'Émirats Arabes Unis', 'Émirienne')
INSERT INTO PAYS VALUES('788', 'TN', 'TUN', 'Tunisia', 'Tunisie', 'Tunisienne')
INSERT INTO PAYS VALUES('792', 'TR', 'TUR', 'Turkey', 'Turquie', 'Turque')
INSERT INTO PAYS VALUES('795', 'TM', 'TKM', 'Turkmenistan', 'Turkménistan', 'Turkmène')
INSERT INTO PAYS VALUES('796', 'TC', 'TCA', 'Turks and Caicos Islands', 'Îles Turks et Caïques', 'Britannique')
INSERT INTO PAYS VALUES('798', 'TV', 'TUV', 'Tuvalu', 'Tuvalu', 'Tuvaluane')
INSERT INTO PAYS VALUES('800', 'UG', 'UGA', 'Uganda', 'Ouganda', 'Ougandaise')
INSERT INTO PAYS VALUES('804', 'UA', 'UKR', 'Ukraine', 'Ukraine', 'Ukrainienne')
INSERT INTO PAYS VALUES('807', 'MK', 'MKD', 'The Former Yugoslav Republic of Macedonia', 'L'ex-République Yougoslave de Macédoine', 'Macédonienne')
INSERT INTO PAYS VALUES('818', 'EG', 'EGY', 'Egypt', 'Égypte', 'Égyptienne')
INSERT INTO PAYS VALUES('826', 'GB', 'GBR', 'United Kingdom', 'Royaume-Uni', 'Britannique')
INSERT INTO PAYS VALUES('833', 'IM', 'IMN', 'Isle of Man', 'Île de Man', 'Britannique')
INSERT INTO PAYS VALUES('834', 'TZ', 'TZA', 'United Republic Of Tanzania', 'République-Unie de Tanzanie', 'Tanzanienne')
INSERT INTO PAYS VALUES('840', 'US', 'USA', 'United States', 'États-Unis', 'Américaine')
INSERT INTO PAYS VALUES('850', 'VI', 'VIR', 'U.S. Virgin Islands', 'Îles Vierges des États-Unis', 'Américaine')
INSERT INTO PAYS VALUES('854', 'BF', 'BFA', 'Burkina Faso', 'Burkina Faso', 'Burkinabée')
INSERT INTO PAYS VALUES('858', 'UY', 'URY', 'Uruguay', 'Uruguay', 'Uruguayenne')
INSERT INTO PAYS VALUES('860', 'UZ', 'UZB', 'Uzbekistan', 'Ouzbékistan', 'Ouzbeke')
INSERT INTO PAYS VALUES('862', 'VE', 'VEN', 'Venezuela', 'Venezuela', 'Vénézuélienne')
INSERT INTO PAYS VALUES('876', 'WF', 'WLF', 'Wallis and Futuna', 'Wallis et Futuna', 'Française')
INSERT INTO PAYS VALUES('882', 'WS', 'WSM', 'Samoa', 'Samoa', 'Samoane')
INSERT INTO PAYS VALUES('887', 'YE', 'YEM', 'Yemen', 'Yémen', 'Yéménite')
INSERT INTO PAYS VALUES('891', 'CS', 'SCG', 'Serbia and Montenegro', 'Serbie-et-Monténégro', 'Serbe')
INSERT INTO PAYS VALUES('894', 'ZM', 'ZMB', 'Zambia', 'Zambie', 'Zambienne')